name: Agent Publishing/Operations

on:
  schedule:
    # Toutes les 2 heures - Maintenir documentation synchronisée
    - cron: '0 */2 * * *'
  workflow_dispatch:  # Permet exécution manuelle

jobs:
  publishing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create communication directory
        run: mkdir -p .github/agents-communication

      - name: Run Agent Publishing
        run: |
          echo "📰 Agent Publishing/Operations - Directeur des Opérations"
          echo "=========================================================="
          echo ""
          node .github/scripts/autonomous-agents/agent-publishing.js

      - name: Commit documentation updates
        run: |
          git config --local user.email "agent-publishing@hubspot-dashboard.com"
          git config --local user.name "Agent Publishing"

          git add README.md SOCIÉTÉ-AUTONOME.md STATUS-AUTO.md .github/agents-communication/publishing-metrics.json || true

          if git diff --staged --quiet; then
            echo "Aucune mise à jour de documentation nécessaire"
          else
            git commit -m "📰 Auto-update: Documentation synchronized by Agent Publishing

Generated by Agent Publishing (Directeur des Opérations)
- README.md updated
- Org chart synchronized
- Status report generated

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"
            git push
            echo "✅ Documentation mise à jour et publiée"
          fi

      - name: Generate workflow summary
        if: always()
        run: |
          echo "## 📰 Agent Publishing - Rapport" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f ".github/agents-communication/publishing-metrics.json" ]; then
            echo "### 📊 Métriques" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat .github/agents-communication/publishing-metrics.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Publication terminée" >> $GITHUB_STEP_SUMMARY
