name: Agent Chef AI-Powered

on:
  schedule:
    # Toutes les 3 heures - Décisions stratégiques avec IA
    - cron: '0 */3 * * *'
  workflow_dispatch:  # Permet exécution manuelle

jobs:
  chef-ai-decisions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create communication directory
        run: mkdir -p .github/agents-communication

      - name: Run Agent Chef AI
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "🤖 Agent Chef de Projet - AI-Powered"
          echo "====================================="
          echo ""

          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "⚠️  ANTHROPIC_API_KEY non configuré - Mode fallback"
            echo "ℹ️  Voir CONFIGURATION-IA.md pour activer l'IA réelle"
            echo ""
          else
            echo "✅ Claude AI activé - Décisions intelligentes"
            echo ""
          fi

          node .github/scripts/autonomous-agents/agent-chef-ai.js

      - name: Commit decisions and task updates
        run: |
          git config --local user.email "agent-chef-ai@hubspot-dashboard.com"
          git config --local user.name "Agent Chef AI"

          git add .github/agents-communication/ RAPPORT-AGENT-CHEF-AI.md || true

          if git diff --staged --quiet; then
            echo "Aucune décision nécessaire ce cycle"
          else
            git commit -m "🤖 AI Decisions: Agent Chef strategic planning

Decisions made by Agent Chef using Claude AI
- Evaluated pending recommendations
- Prioritized based on business impact
- Created tasks for approved items
- Applied intelligent context-aware decisions

Mode: $([ -z "$ANTHROPIC_API_KEY" ] && echo "Fallback (configure ANTHROPIC_API_KEY)" || echo "AI-Powered ✅")

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"
            git push
            echo "✅ Décisions committées"
          fi
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Check for escalations
        run: |
          if [ -f ".github/agents-communication/user-escalations.json" ]; then
            echo "📞 Vérification des escalations..."

            PENDING_COUNT=$(cat .github/agents-communication/user-escalations.json | grep -o '"status": "pending"' | wc -l)

            if [ "$PENDING_COUNT" -gt 0 ]; then
              echo ""
              echo "🔴 ATTENTION: $PENDING_COUNT escalation(s) en attente"
              echo "Les agents ont besoin de votre aide!"
              echo ""
              echo "Voir: .github/agents-communication/user-escalations.json"
              echo ""
            fi
          fi

      - name: Generate workflow summary
        if: always()
        run: |
          echo "## 🤖 Agent Chef AI - Rapport" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "**Mode**: ⚠️ Fallback (règles simples)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "ℹ️ Configurer \`ANTHROPIC_API_KEY\` pour activer l'IA réelle" >> $GITHUB_STEP_SUMMARY
            echo "Voir: [CONFIGURATION-IA.md](../CONFIGURATION-IA.md)" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Mode**: ✅ AI-Powered (Claude)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Décisions prises avec intelligence artificielle" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f "RAPPORT-AGENT-CHEF-AI.md" ]; then
            echo "### 📊 Rapport complet" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Voir: [RAPPORT-AGENT-CHEF-AI.md](../RAPPORT-AGENT-CHEF-AI.md)" >> $GITHUB_STEP_SUMMARY
          fi

          # Afficher escalations si présentes
          if [ -f ".github/agents-communication/user-escalations.json" ]; then
            PENDING_COUNT=$(cat .github/agents-communication/user-escalations.json | grep -o '"status": "pending"' | wc -l || echo "0")

            if [ "$PENDING_COUNT" -gt 0 ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### 🔴 Escalations" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "⚠️ **$PENDING_COUNT escalation(s)** en attente de votre action" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "Les agents ont besoin de votre aide (permissions, API keys, décisions)." >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "Détails: \`.github/agents-communication/user-escalations.json\`" >> $GITHUB_STEP_SUMMARY
            fi
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Cycle terminé" >> $GITHUB_STEP_SUMMARY
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
