name: 🏢 Entreprise Autonome IA

# L'ENTREPRISE COMPLÈTE qui améliore le dashboard continuellement
# Toutes les heures: TOUTE la boucle d'entreprise tourne

on:
  schedule:
    # Toutes les heures - La boucle complète
    - cron: '0 * * * *'
  workflow_dispatch:  # Manuel
  push:
    branches: [main]
    paths:
      - 'public/index.html'
      - 'CAHIER-DES-CHARGES.md'
      - 'RAPPORT-FINAL-AUDIT.md'

permissions:
  contents: write
  issues: write
  actions: read

jobs:
  # ORCHESTRATEUR - Lance toute la boucle
  run-company:
    name: 🏢 Boucle Entreprise Complète
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap Tasks (si vide)
        run: |
          chmod +x .github/scripts/autonomous-agents/bootstrap-tasks.js
          node .github/scripts/autonomous-agents/bootstrap-tasks.js

      - name: Run Orchestrateur - Toute la boucle
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "🏢 LANCEMENT DE L'ENTREPRISE AUTONOME IA"
          echo "=========================================="
          echo ""
          chmod +x .github/scripts/autonomous-agents/orchestrator.js
          node .github/scripts/autonomous-agents/orchestrator.js

      - name: Commit tous les changements
        run: |
          git config user.name "Autonomous Company Bot"
          git config user.email "noreply@company.bot"

          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "feat: Boucle entreprise autonome - Améliorations automatiques

            🏢 ENTREPRISE AUTONOME IA:
            - Producteur AI: Analyse problèmes
            - Visionnaire AI: Propose features
            - RH AI: Recrute agents
            - Chef AI: Priorise et décide
            - Dev: Implémente
            - QA: Teste
            - Debugger: Fixe
            - Aiguilleur: Surveille

            Tous les rapports et fixes appliqués automatiquement.

            🤖 Generated with [Claude Code](https://claude.com/claude-code)

            Co-Authored-By: Claude <noreply@anthropic.com>"

            git push origin main
            echo "✅ Changements committés et pushés"
          else
            echo "ℹ️  Pas de changements"
          fi

      - name: Upload tous les rapports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: company-reports
          path: |
            RAPPORT-*.md
            .github/agents-communication/

  # RÉSUMÉ & METRICS
  summary:
    name: 📊 Résumé Entreprise
    runs-on: ubuntu-latest
    needs: run-company
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download rapports
        uses: actions/download-artifact@v4
        with:
          name: company-reports

      - name: Generate Summary
        run: |
          echo "📊 RÉSUMÉ - ENTREPRISE AUTONOME IA"
          echo "======================================"
          echo ""
          echo "**Date**: $(date +"%Y-%m-%d %H:%M:%S")"
          echo "**Run**: #${{ github.run_number }}"
          echo ""
          echo "## Status"
          echo ""
          echo "| Job | Status |"
          echo "|-----|--------|"
          echo "| Boucle Entreprise | ${{ needs.run-company.result }} |"
          echo ""

          # Score QA si disponible
          if [ -f RAPPORT-AGENT-QA.md ]; then
            SCORE=$(grep "Score" RAPPORT-AGENT-QA.md | grep -o '[0-9]\+' | head -1)
            echo "## Dashboard Quality"
            echo ""
            echo "**Score QA**: $SCORE/100"
            echo ""
          fi

          # Tasks
          if [ -f .github/agents-communication/tasks.json ]; then
            TASKS=$(grep -o '"id"' .github/agents-communication/tasks.json | wc -l)
            echo "**Tâches actives**: $TASKS"
            echo ""
          fi

          echo "## Prochaine Exécution"
          echo ""
          echo "⏰ Dans 1 heure (automatique)"
          echo ""
          echo "---"
          echo "🏢 Entreprise Autonome IA - Dashboard HubSpot"
