name: 🚦 Agent Aiguilleur (Traffic Controller)

# Workflow de monitoring qui surveille les autres workflows
# et prévient les conflits / boucles infinies
#
# Responsabilités:
# - Monitorer l'état des workflows
# - Détecter les conflits
# - Prévenir les boucles infinies
# - Générer des alertes
# - Maintenir un rapport de santé

on:
  schedule:
    # Toutes les heures (monitoring fréquent)
    - cron: '0 * * * *'
  workflow_dispatch:  # Manuel
  # Note: Ne se déclenche PAS sur push pour éviter de surcharger

jobs:
  # JOB 1: MONITORING DES WORKFLOWS
  monitor:
    name: 🚦 Monitoring Workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install GitHub CLI
        run: |
          # gh CLI est pré-installé sur GitHub Actions
          gh --version

      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "✅ GitHub CLI configuré"

      - name: Exécuter Agent Aiguilleur
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🚦 AGENT AIGUILLEUR - Démarrage"
          echo "================================================"
          echo ""

          # Donner les permissions d'exécution
          chmod +x .github/scripts/autonomous-agents/agent-aiguilleur.js

          # Exécuter l'agent
          node .github/scripts/autonomous-agents/agent-aiguilleur.js

          echo ""
          echo "✅ Agent Aiguilleur terminé"

      - name: Upload rapport
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: traffic-controller-report
          path: RAPPORT-AGENT-AIGUILLEUR.md

      - name: Commit rapport si changé
        run: |
          git config user.name "Traffic Controller Bot"
          git config user.email "noreply@traffic-controller.bot"

          if [ -n "$(git status --porcelain)" ]; then
            git add RAPPORT-AGENT-AIGUILLEUR.md
            git commit -m "docs: Mise à jour rapport Agent Aiguilleur [skip ci]

            🤖 Generated with [Claude Code](https://claude.com/claude-code)

            Co-Authored-By: Claude <noreply@anthropic.com>"

            git push origin main || echo "⚠️  Push échoué - pas critique"

            echo "✅ Rapport committé"
          else
            echo "ℹ️  Pas de changement dans le rapport"
          fi

  # JOB 2: ALERTES SI PROBLÈMES CRITIQUES
  alert:
    name: 🚨 Alertes Critiques
    runs-on: ubuntu-latest
    needs: monitor
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download rapport
        uses: actions/download-artifact@v3
        with:
          name: traffic-controller-report

      - name: Vérifier score de santé
        run: |
          echo "🔍 Vérification score de santé des workflows"
          echo "================================================"

          if [ -f RAPPORT-AGENT-AIGUILLEUR.md ]; then
            # Extraire le score du rapport
            SCORE=$(grep "Score Global" RAPPORT-AGENT-AIGUILLEUR.md | grep -o '[0-9]\+' | head -1 || echo "100")

            echo "📊 Score de santé: $SCORE/100"

            if [ "$SCORE" -lt 50 ]; then
              echo ""
              echo "🔴 ALERTE CRITIQUE: Score < 50"
              echo "   Action requise: Vérifier immédiatement les workflows"
              echo "   Voir rapport détaillé: RAPPORT-AGENT-AIGUILLEUR.md"
              echo ""
              echo "::error::Workflows en état critique (score: $SCORE/100)"

            elif [ "$SCORE" -lt 70 ]; then
              echo ""
              echo "🟠 AVERTISSEMENT: Score < 70"
              echo "   Action recommandée: Surveiller la situation"
              echo ""
              echo "::warning::Workflows en état dégradé (score: $SCORE/100)"

            else
              echo ""
              echo "✅ État normal - workflows en bonne santé"
            fi
          else
            echo "⚠️  Rapport non trouvé"
          fi

  # JOB 3: RÉSUMÉ
  summary:
    name: 📊 Résumé
    runs-on: ubuntu-latest
    needs: [monitor, alert]
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Afficher résumé
        run: |
          echo "📊 RÉSUMÉ - AGENT AIGUILLEUR"
          echo "================================================"
          echo ""
          echo "**Date**: $(date +"%Y-%m-%d %H:%M:%S")"
          echo "**Run**: #${{ github.run_number }}"
          echo ""
          echo "## Jobs"
          echo ""
          echo "| Job | Status |"
          echo "|-----|--------|"
          echo "| Monitor | ${{ needs.monitor.result }} |"
          echo "| Alert | ${{ needs.alert.result }} |"
          echo ""
          echo "## Prochaine Exécution"
          echo ""
          echo "⏰ Dans 1 heure (automatique)"
          echo ""
          echo "---"
          echo "🚦 Agent Aiguilleur - Traffic Controller pour workflows GitHub Actions"
